### ISSUE TITLE
problème de connexion  à l'Eco-Devices en local depuis HA

### ISSUE THREAD

**Issue by njm504** [Aohzan/ecodevices#61]
Bonjour,

il est impossible de se connecter à l'ecodevices depuis ce jour:

config:
Méthode d'installation: Home Assistant OS
Core: 2025.6.1
Supervisor: 2025.05.5
Operating System: 15.2
Interface utilisateur: 20250531.3

journaux:
Enregistreur: homeassistant.helpers.frame
Source: helpers/frame.py:335
S'est produit pour la première fois: 11:19:20 (1 occurrence)
Dernier enregistrement: 11:19:20

Detected that custom integration 'ecodevices' sets option flow config_entry explicitly, which is deprecated at custom_components/ecodevices/config_flow.py, line 123: self.config_entry: ConfigEntry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/Aohzan/ecodevices/issues

Merci pour votre aide.

**Comment by njm504** [comment]
Bonjour,

Oui effectivement, j'ai trouvé ceci:

Enregistreur: homeassistant.config_entries
Source: config_entries.py:749
S'est produit pour la première fois: 09:22:45 (2 occurrences)
Dernier enregistrement: 09:23:11

Error setting up entry Eco-Devices 192.168.0.19:90 for ecodevices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecodevices/__init__.py", line 136, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

Il est indiqué que c'est un problème de configuration. Hors je me connecte sans problème à l'ecodevices en local avec les même éléments. C'est le bon compteur qui est choisi (compteur eau).

Si vous avez besoin d'autres informations, je suis à votre disposition.

Merci.

**Comment by njm504** [comment]
Je suis désolé j'ai fermé le sujet par intention. Je m'en excuse.

**Comment by Aohzan** [comment]
je pense que l'intégration n'est pas à jour
